### ISSUE TITLE
Using the generated-sources from another module

### ISSUE THREAD

**Issue by kjussakov** [pwall567/json-kotlin-gradle#4]
Hi,

First of all big thanks for the great library!
I am not sure if this is really an issue with the plugin or more how I use it in my setup.
I have gradle subproject "model" where the only thing I have is the json schema files in src/main/resources/schema and no other sources.
build.gradle.kts:
```
configure<JSONSchemaCodegen> {
    packageName.set("com.example")
    inputs {
        inputComposite {
            file.set(file("src/main/resources/schema/sample_schema.json"))
            pointer.set("/definitions")
        }
    }
}

sourceSets.main {
    java.srcDirs("build/generated-sources/kotlin")
}
```

Then in another subproject "service" I have the following:
```
dependencies {
    implementation(project(":model"))
}
```

In the top level settings.gradle.kts I have:

```
rootProject.name = "example"
include("model")
include("service")
```

when I execute:
`./gradlew clean build`

I always get errors in "service" for Unresolved reference to classes which should have been generated from the `src/main/resources/schema`
And indeed the `build/generated-sources` folder in "model" is missing even though the build and the jars in `build/libs` are generated
indicating there is some problem with the build not depending on the generated task.
The same issue is happening when I run:

`./gradlew co360-model:build`

The strange thing is if I run the build task from Intellij  gradle window the generateKotlin task is executed and the generated-sources are build. I am not able to understand what Intellij is executing under the hood.

Any hints are highly appreciated.

Best regards,
Rumen

**Comment by kjussakov** [comment]
Hi Peter,

Thank you for taking time to answer! I myself am not Gradle expert either and have tried the `dependsOn` path but without much success before posting here.
In any case I will close this since it is not really an issue with the plugin.
If I find a solution for it I will post it here.

Best regards,
Rumen

**Comment by gsnerf** [comment]
I actually believe the defaults to be faulty for usage in multi-module builds. In these cases the root directory is different and the defaults will always try to find the schema files and build it based on the root project, not the sub project the files are actually supposed to be build.

@kjussakov: as a workaround for your case you would need define both inputs and outputs to contain a reference to `${project.projectDir}` for it to work correctly. Example below:

```gradle
configure<JSONSchemaCodegen> {
    inputs {
        inputFile(file("${project.projectDir}/src/main/resources/schema")) // if not in the default location
    }
    outputDir.set(file("${project.projectDir}/build/generated-sources/kotlin"))
}
```

But again, I think that shouldn't be necessary and the defaults should be corrected to already mind the project directory.
