### ISSUE TITLE
Please update docs to specify that `configure` should appear _after_ `apply`

### ISSUE THREAD

**Issue by gino-m** [pwall567/json-kotlin-gradle#9]
This could have saved me considerable time debugging. Thank you!

**Comment by pwall567** [comment]
You're not alone in spending a great deal of time debugging Gradle build files!

I agree that this would be a helpful addition to the README and I have updated it accordingly.

I will also endeavour to provide full examples that users can use as a starting point for their own build files.

-Peter

**Comment by gino-m** [comment]
> You're not alone in spending a great deal of time debugging Gradle build files!
> 
> I agree that this would be a helpful addition to the README and I have updated it accordingly.
> 
> I will also endeavour to provide full examples that users can use as a starting point for their own build files.
> 
> -Peter

Thanks, Peter, for adding this to the README!

As mentioned in #6, indeed 90% of the trouble I've had is certainly due to my lack of understanding of Gradle, especially the Kotlin DSL. Thank you for all your hard work and for a great tool!
